-- Kapsamlı SEO çalışması, 2. adım (devam): İngilizce sayfalar.
-- Bkz. V44 — aynı mantık, EN sayfalar için.

UPDATE page SET seo_title = 'Accessibility Statement — Hacettepe University IT', seo_keywords = 'Accessibility Statement, Hacettepe University, Department of Information Technology' WHERE id = 100;
UPDATE page SET seo_title = 'Hacettepe University Alumni Account — Hacettepe University IT', seo_keywords = 'Hacettepe University Alumni Account, Hacettepe University, Department of Information Technology' WHERE id = 125;
UPDATE page SET seo_title = 'ANSYS Software Announcement — Hacettepe University IT', seo_keywords = 'ANSYS Software Announcement, Hacettepe University, Department of Information Technology' WHERE id = 163;
UPDATE page SET seo_title = 'Archive — Hacettepe University IT', seo_keywords = 'Archive, Hacettepe University, Department of Information Technology' WHERE id = 159;
UPDATE page SET seo_title = 'Hacettepe University Content Management — Hacettepe University IT', seo_keywords = 'Hacettepe University Content Management System, Hacettepe University, Department of Information Technology' WHERE id = 173;
UPDATE page SET seo_title = 'Committees — Hacettepe University IT', seo_keywords = 'Committees, Hacettepe University, Department of Information Technology' WHERE id = 93;
UPDATE page SET seo_title = 'About HU Internet Connection — Hacettepe University IT', seo_keywords = 'About Internet Connection, Hacettepe University, Department of Information Technology' WHERE id = 174;
UPDATE page SET seo_title = 'Contact Information — Hacettepe University IT', seo_keywords = 'Contact Information, Hacettepe University, Department of Information Technology' WHERE id = 98;
UPDATE page SET seo_title = 'Database Query Page — Hacettepe University IT', seo_keywords = 'Database Query Page, Hacettepe University, Department of Information Technology' WHERE id = 161;
UPDATE page SET seo_title = 'Disclaimer — Hacettepe University IT', seo_keywords = 'Disclaimer, Hacettepe University, Department of Information Technology' WHERE id = 99;
UPDATE page SET seo_title = 'Useful Documents and Links — Hacettepe University IT', seo_keywords = 'Useful Documents Links, Hacettepe University, Department of Information Technology' WHERE id = 175;
UPDATE page SET seo_title = 'Information and Documents — Hacettepe University IT', seo_keywords = 'Information Documents, Hacettepe University, Department of Information Technology' WHERE id = 145;
UPDATE page SET seo_title = 'HUNET - BEYTEPE Dormitory Access Protocol — Hacettepe University IT', seo_keywords = 'HUNET BEYTEPE Dormitory Access Protocol, Hacettepe University, Department of Information Technology' WHERE id = 122;
UPDATE page SET seo_title = 'Rules for Dormitories and Student Houses — Hacettepe University IT', seo_keywords = 'Rules Dormitories Student Houses, Hacettepe University, Department of Information Technology' WHERE id = 127;
UPDATE page SET seo_title = 'Electronic Signature Usage Guide — Hacettepe University IT', seo_keywords = 'Electronic Signature Usage Guide, Hacettepe University, Department of Information Technology' WHERE id = 176;
UPDATE page SET seo_title = 'About E-Signature — Hacettepe University IT', seo_keywords = 'About Signature, Hacettepe University, Department of Information Technology' WHERE id = 149;
UPDATE page SET seo_title = 'Application — Hacettepe University IT', seo_keywords = 'Application, Hacettepe University, Department of Information Technology' WHERE id = 177;
UPDATE page SET seo_title = 'Certificate Cancellation — Hacettepe University IT', seo_keywords = 'Certificate Cancellation, Hacettepe University, Department of Information Technology' WHERE id = 148;
UPDATE page SET seo_title = 'I Have Received My Certificate, What Should — Hacettepe University IT', seo_keywords = 'Have Received Certificate What Should Do?, Hacettepe University, Department of Information Technology' WHERE id = 140;
UPDATE page SET seo_title = 'E-Signature Frequently Asked Questions — Hacettepe University IT', seo_keywords = 'Signature Frequently Asked Questions, Hacettepe University, Department of Information Technology' WHERE id = 157;
UPDATE page SET seo_title = 'Certificate Information Update — Hacettepe University IT', seo_keywords = 'Certificate Information Update, Hacettepe University, Department of Information Technology' WHERE id = 154;
UPDATE page SET seo_title = 'Java Settings — Hacettepe University IT', seo_keywords = 'Java Settings, Hacettepe University, Department of Information Technology' WHERE id = 151;
UPDATE page SET seo_title = 'Legislation — Hacettepe University IT', seo_keywords = 'Legislation, Hacettepe University, Department of Information Technology' WHERE id = 178;
UPDATE page SET seo_title = 'Password Procedures — Hacettepe University IT', seo_keywords = 'Password Procedures, Hacettepe University, Department of Information Technology' WHERE id = 155;
UPDATE page SET seo_title = 'Desktop Help — Hacettepe University IT', seo_keywords = 'Desktop Help, Hacettepe University, Department of Information Technology' WHERE id = 139;
UPDATE page SET seo_title = 'Certificate Renewal — Hacettepe University IT', seo_keywords = 'Certificate Renewal, Hacettepe University, Department of Information Technology' WHERE id = 152;
UPDATE page SET seo_title = 'Security Word — Hacettepe University IT', seo_keywords = 'Security Word, Hacettepe University, Department of Information Technology' WHERE id = 143;
UPDATE page SET seo_title = 'Unit E-Signature Officers — Hacettepe University IT', seo_keywords = 'Unit Signature Officers, Hacettepe University, Department of Information Technology' WHERE id = 179;
UPDATE page SET seo_title = 'Certificate Update — Hacettepe University IT', seo_keywords = 'Certificate Update, Hacettepe University, Department of Information Technology' WHERE id = 153;
UPDATE page SET seo_title = 'Application Workflow — Hacettepe University IT', seo_keywords = 'Application Workflow, Hacettepe University, Department of Information Technology' WHERE id = 142;
UPDATE page SET seo_title = 'E-mail Operations — Hacettepe University IT', seo_keywords = 'mail Operations, Hacettepe University, Department of Information Technology' WHERE id = 180;
UPDATE page SET seo_title = 'Opening a New Email Account — Hacettepe University IT', seo_keywords = 'Opening New Email Account, Hacettepe University, Department of Information Technology' WHERE id = 181;
UPDATE page SET seo_title = 'Old E-mail Backup Procedures (Video Guide) — Hacettepe University IT', seo_keywords = 'Old mail Backup Procedures Video Guide, Hacettepe University, Department of Information Technology' WHERE id = 160;
UPDATE page SET seo_title = 'Information on the New Hacettepe University — Hacettepe University IT', seo_keywords = 'Information New Hacettepe University Email Service, Hacettepe University, Department of Information Technology' WHERE id = 182;
UPDATE page SET seo_title = 'External Access Rules — Hacettepe University IT', seo_keywords = 'External Access Rules, Hacettepe University, Department of Information Technology' WHERE id = 103;
UPDATE page SET seo_title = 'Frequently Asked Questions — Hacettepe University IT', seo_keywords = 'Frequently Asked Questions, Hacettepe University, Department of Information Technology' WHERE id = 183;
UPDATE page SET seo_title = 'Forms — Hacettepe University IT', seo_keywords = 'Forms, Hacettepe University, Department of Information Technology' WHERE id = 146;
UPDATE page SET seo_title = 'Hardware — Hacettepe University IT', seo_keywords = 'Hardware, Hacettepe University, Department of Information Technology' WHERE id = 102;
UPDATE page SET seo_title = 'HUNET Usage Principles — Hacettepe University IT', seo_keywords = 'HUNET Usage Principles, Hacettepe University, Department of Information Technology' WHERE id = 184;
UPDATE page SET seo_title = 'Information Security Management System — Hacettepe University IT', seo_keywords = 'Information Security Management System, Hacettepe University, Department of Information Technology' WHERE id = 111;
UPDATE page SET seo_title = 'Precautions for Computer Accidents — Hacettepe University IT', seo_keywords = 'Precautions Computer Accidents, Hacettepe University, Department of Information Technology' WHERE id = 113;
UPDATE page SET seo_title = 'PC Laboratory Usage Rules — Hacettepe University IT', seo_keywords = 'Laboratory Usage Rules, Hacettepe University, Department of Information Technology' WHERE id = 185;
UPDATE page SET seo_title = 'E-Mail Filtering Policies — Hacettepe University IT', seo_keywords = 'Mail Filtering Policies, Hacettepe University, Department of Information Technology' WHERE id = 133;
UPDATE page SET seo_title = 'E-Mail Lists Usage Rules — Hacettepe University IT', seo_keywords = 'Mail Lists Usage Rules, Hacettepe University, Department of Information Technology' WHERE id = 186;
UPDATE page SET seo_title = 'MATLAB Software for Our Students — Hacettepe University IT', seo_keywords = 'MATLAB Software Our Students, Hacettepe University, Department of Information Technology' WHERE id = 164;
UPDATE page SET seo_title = 'Mission and Vision — Hacettepe University IT', seo_keywords = 'Mission Vision, Hacettepe University, Department of Information Technology' WHERE id = 97;
UPDATE page SET seo_title = 'Network Infrastructure — Hacettepe University IT', seo_keywords = 'Network Infrastructure, Hacettepe University, Department of Information Technology' WHERE id = 101;
UPDATE page SET seo_title = 'Notices — Hacettepe University IT', seo_keywords = 'Notices, Hacettepe University, Department of Information Technology' WHERE id = 168;
UPDATE page SET seo_title = 'Error!.. — Hacettepe University IT', seo_keywords = 'Error!.., Hacettepe University, Department of Information Technology' WHERE id = 200;
UPDATE page SET seo_title = 'Applications Accessible from Within the — Hacettepe University IT', seo_keywords = 'Applications Accessible from Within Campus, Hacettepe University, Department of Information Technology' WHERE id = 169;
UPDATE page SET seo_title = 'Secure E-Mail Information Notice — Hacettepe University IT', seo_keywords = 'Secure Mail Information Notice, Hacettepe University, Department of Information Technology' WHERE id = 170;
UPDATE page SET seo_title = 'Error!.. — Hacettepe University IT', seo_keywords = 'Error!.., Hacettepe University, Department of Information Technology' WHERE id = 198;
UPDATE page SET seo_title = 'CONTRACTED IT PERSONNEL EXAMINATION — Hacettepe University IT', seo_keywords = 'CONTRACTED PERSONNEL EXAMINATION ANNOUNCEMENT, Hacettepe University, Department of Information Technology' WHERE id = 187;
UPDATE page SET seo_title = 'İŞKUR Youth Programme – Occupational Health — Hacettepe University IT', seo_keywords = 'İŞKUR Youth Programme Occupational Health Safety, Hacettepe University, Department of Information Technology' WHERE id = 188;
UPDATE page SET seo_title = 'Contracted IT Personnel Examination — Hacettepe University IT', seo_keywords = 'Contracted Personnel Examination Announcement, Hacettepe University, Department of Information Technology' WHERE id = 162;
UPDATE page SET seo_title = 'Office 365 — Hacettepe University IT', seo_keywords = 'Office 365, Hacettepe University, Department of Information Technology' WHERE id = 126;
UPDATE page SET seo_title = 'Organisation Chart — Hacettepe University IT', seo_keywords = 'Organisation Chart, Hacettepe University, Department of Information Technology' WHERE id = 197;
UPDATE page SET seo_title = 'General Overview — Hacettepe University IT', seo_keywords = 'General Overview, Hacettepe University, Department of Information Technology' WHERE id = 196;
UPDATE page SET seo_title = 'Error!.. — Hacettepe University IT', seo_keywords = 'Error!.., Hacettepe University, Department of Information Technology' WHERE id = 199;
UPDATE page SET seo_title = 'Web Service for Personal Web Pages — Hacettepe University IT', seo_keywords = 'Web Service Personal Pages, Hacettepe University, Department of Information Technology' WHERE id = 123;
UPDATE page SET seo_title = 'Proxy Settings — Hacettepe University IT', seo_keywords = 'Proxy Settings, Hacettepe University, Department of Information Technology' WHERE id = 158;
UPDATE page SET seo_title = 'Proxy-Spam Control — Hacettepe University IT', seo_keywords = 'Proxy Spam Control, Hacettepe University, Department of Information Technology' WHERE id = 189;
UPDATE page SET seo_title = 'SAS (Statistical Analysis Software) — Hacettepe University IT', seo_keywords = 'SAS Statistical Analysis Software Announcement, Hacettepe University, Department of Information Technology' WHERE id = 165;
UPDATE page SET seo_title = 'Viruses and Security Recommendations — Hacettepe University IT', seo_keywords = 'Viruses Security Recommendations, Hacettepe University, Department of Information Technology' WHERE id = 119;
UPDATE page SET seo_title = 'Security Policy — Hacettepe University IT', seo_keywords = 'Security Policy, Hacettepe University, Department of Information Technology' WHERE id = 92;
UPDATE page SET seo_title = 'Service Groups — Hacettepe University IT', seo_keywords = 'Service Groups, Hacettepe University, Department of Information Technology' WHERE id = 67;
UPDATE page SET seo_title = 'Web Service for Unit Web Pages — Hacettepe University IT', seo_keywords = 'Web Service Unit Pages, Hacettepe University, Department of Information Technology' WHERE id = 190;
UPDATE page SET seo_title = 'Licensed Software Server — Hacettepe University IT', seo_keywords = 'Licensed Software Server, Hacettepe University, Department of Information Technology' WHERE id = 138;
UPDATE page SET seo_title = 'About SPAM and PHISHING — Hacettepe University IT', seo_keywords = 'About SPAM PHISHING, Hacettepe University, Department of Information Technology' WHERE id = 191;
UPDATE page SET seo_title = 'IBM SPSS Software for Our Students — Hacettepe University IT', seo_keywords = 'IBM SPSS Software Our Students, Hacettepe University, Department of Information Technology' WHERE id = 192;
UPDATE page SET seo_title = 'Staff — Hacettepe University IT', seo_keywords = 'Staff, Hacettepe University, Department of Information Technology' WHERE id = 94;
UPDATE page SET seo_title = 'Framework Rules for Our Students Regarding — Hacettepe University IT', seo_keywords = 'Framework Rules Our Students Regarding Hacettepe, Hacettepe University, Department of Information Technology' WHERE id = 193;
UPDATE page SET seo_title = 'Regarding the Removal of 50th-Anniversary — Hacettepe University IT', seo_keywords = 'Regarding Removal 50th Anniversary Logos from, Hacettepe University, Department of Information Technology' WHERE id = 167;
UPDATE page SET seo_title = 'Recommendations for Protection against — Hacettepe University IT', seo_keywords = 'Recommendations Protection against Computer Viruses Attacks, Hacettepe University, Department of Information Technology' WHERE id = 194;
UPDATE page SET seo_title = 'Information and Connection Guides regarding — Hacettepe University IT', seo_keywords = 'Information Connection Guides regarding VPN system, Hacettepe University, Department of Information Technology' WHERE id = 135;
UPDATE page SET seo_title = 'WEB Page Publishing Principles — Hacettepe University IT', seo_keywords = 'WEB Page Publishing Principles, Hacettepe University, Department of Information Technology' WHERE id = 137;
UPDATE page SET seo_title = 'WEB Services — Hacettepe University IT', seo_keywords = 'WEB Services, Hacettepe University, Department of Information Technology' WHERE id = 136;
UPDATE page SET seo_title = 'Email — Hacettepe University IT', seo_keywords = 'Email, Hacettepe University, Department of Information Technology' WHERE id = 115;
UPDATE page SET seo_title = 'Wireless Access Services — Hacettepe University IT', seo_keywords = 'Wireless Access Services, Hacettepe University, Department of Information Technology' WHERE id = 195;
