/* Eski adreslerin yeni İngilizce adreslere eşlemesi.

   Mevcut site arama motorlarında ve dış bağlantılarda eski adreslerle
   kayıtlı olduğu için, eski adresler kalıcı yönlendirme (301) ile yeni
   adreslere taşınır.

   Bu dosya tools/slug-map.js kaynağından üretilmiştir; elle düzenlemeyin. */

export const LEGACY_ROUTES: Record<string, string> = {
  '/tr/anasayfa': '/tr/home',
  '/tr/geneltanitim': '/tr/overview',
  '/tr/yonetim': '/tr/org-chart',
  '/tr/misyonvizyon': '/tr/mission-vision',
  '/tr/bilgikorumaanapolitikamiz': '/tr/security-policy',
  '/tr/personel': '/tr/staff',
  '/tr/organizasyonsemasi': '/tr/org-chart',
  '/tr/kk': '/tr/committees',
  '/tr/webser': '/tr/web-services',
  '/tr/hu-iys': '/tr/cms',
  '/tr/kablosuz': '/tr/wireless',
  '/tr/yazilim': '/tr/software',
  '/tr/bilgidokuman': '/tr/documents',
  '/tr/eposta': '/tr/email',
  '/tr/e-posta': '/tr/webmail',
  '/tr/sss': '/tr/faq',
  '/tr/formlar': '/tr/forms',
  '/tr/bgys': '/tr/isms',
  '/tr/tarama': '/tr/mail-filtering',
  '/tr/yayim': '/tr/web-policy',
  '/tr/ogr_kural': '/tr/dorm-rules',
  '/tr/pc_salon': '/tr/lab-rules',
  '/tr/posta_kural': '/tr/mailing-lists',
  '/tr/hunet_kurallar': '/tr/hunet-policy',
  '/tr/bilisim_ilke': '/tr/student-rules',
  '/tr/hunet_protokol': '/tr/dorm-access',
  '/tr/altyapi': '/tr/network',
  '/tr/donanim': '/tr/hardware',
  '/tr/erisim': '/tr/external-access',
  '/tr/iletisim': '/tr/contact',
  '/tr/sorumluluksiniri': '/tr/disclaimer',
  '/tr/erisilebilirlik': '/tr/accessibility',
  '/tr/mezuneposta': '/tr/alumni-email',
  '/tr/arsiv': '/tr/archive',
  '/tr/servis': '/tr/services',
  '/tr/kisisel': '/tr/personal-pages',
  '/tr/guvenlik': '/tr/security',
  '/tr/bil_onlem': '/tr/it-security-tips',
  '/tr/baglanti_onlem': '/tr/connection-security',
  '/tr/dokuman_link': '/tr/document-links',
  '/tr/epostaalma': '/tr/email-account',
  '/tr/proxy_spam_kntr': '/tr/proxy-spam',
  '/tr/eposta_gecis': '/tr/email-migration',
  '/tr/ilan_280425': '/tr/notice-280425',
  '/tr/duy_iskur280225': '/tr/notice-iskur-280225',
  '/tr/ilan': '/tr/notices',
  '/tr/duyuru121120': '/tr/notice-121120',
  '/tr/duyuru110520': '/tr/notice-110520',
  '/tr/eposta051218': '/tr/notice-051218',
  '/tr/spss081118': '/tr/spss-081118',
  '/tr/matlabogr061118': '/tr/matlab-061118',
  '/tr/sas191018': '/tr/sas-191018',
  '/tr/ansysduy011018': '/tr/ansys-011018',
  '/tr/stylecc50kaldirilmasi': '/tr/stylecc50-removal',
  '/tr/d_050416': '/tr/notice-050416',
  '/tr/dblidyasorgui': '/tr/database-query',
  '/tr/viruslere-karsi-korunma': '/tr/virus-protection',
  '/tr/eski_eposta_yedekalma_video': '/tr/email-backup-video',
  '/tr/kurumsalsema180117': '/tr/notice-180117',
  '/en/anasayfa': '/en/home',
  '/en/mv': '/en/mission-vision',
  '/en/yonetim': '/en/org-chart',
  '/en/grup': '/en/service-groups',
  '/en/iletisim': '/en/contact'
};
